# Generated by Django 5.0.1 on 2025-11-23 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='users.user', verbose_name='Joueur demandeur')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='teams.team', verbose_name='Équipe ciblée')),
            ],
            options={
                'verbose_name': "Demande d'Adhésion",
                'verbose_name_plural': "Demandes d'Adhésion",
                'db_table': 'join_requests',
                'ordering': ['-created_at'],
                'unique_together': {('player', 'team')},
            },
        ),
    ]
