@baseUrl = http://127.0.0.1:8000/api
@playerId = 6
@teamId = cb9376dc-c762-427c-b043-ff2a271dc41c
@userId = a4ac4d34-fd0d-4554-85f8-6d7542510616
@organizerId = fb9ad348-d532-4849-90c3-a0135fb9ab5c
@joinRequestId = 3875e8c6-d9e3-47f9-8cd1-0ca4cba83062


### ================================
### 0) Lister les équipes (récupérer un id de team)
### ================================
GET {{baseUrl}}/join-requests/
Content-Type: application/json


### ================================
### 1) Créer une demande d’adhésion
### ================================
### Remplace ICI_TEAM_ID par un id d’équipe valide
POST {{baseUrl}}/join-requests/
Content-Type: application/json

{
  "user_id":"{{userId}}",
  "team": "{{teamId}}",
  "message": "Je veux rejoindre l'équipe 🙂"
}


### ================================
### 2) Voir MES demandes (joueur)
### ================================
### Remplace ICI_PLAYER_ID par l'id d'un user (joueur)
GET {{baseUrl}}/join-requests/my/?player_id={{userId}}
Content-Type: application/json


### ================================
### 3) Voir les demandes reçues (organisateur)
### ================================
### Remplace ICI_ORGANIZER_ID par l'id d'un user organisateur
GET {{baseUrl}}/join-requests/received/?organizer_id={{organizerId}}
Content-Type: application/json


### ================================
### 4) Accepter une demande
### ================================
### Remplace ICI_JOINREQUEST_ID par l'id d'une join request
PATCH {{baseUrl}}/join-requests/{{joinRequestId}}/
Content-Type: application/json

{
  "status": "accepted"
}


### ================================
### 5) Refuser une demande
### ================================
PATCH {{baseUrl}}/join-requests/{{joinRequestId}}/
Content-Type: application/json

{
  "status": "rejected"
}
