@baseUrl = http://127.0.0.1:8000/api
@playerId = 6
@teamId = 6369e960-d1c3-46c3-b920-2e89fb9b77dc
@organizerId = fb9ad348-d532-4849-90c3-a0135fb9ab5c


### ================================
### 0) Lister les équipes (récupérer un id de team)
### ================================
GET {{baseUrl}}/join-requests/
Content-Type: application/json


### ================================
### 1) Créer une demande d’adhésion
### ================================
### Remplace ICI_TEAM_ID par un id d’équipe valide
POST {{baseUrl}}/join-requests/
Content-Type: application/json

{
  "team": "83d7499f-e077-4206-9a82-6d57a0e9bbf1",
  "message": "Je veux rejoindre l'équipe 🙂"
}


### ================================
### 2) Voir MES demandes (joueur)
### ================================
### Remplace ICI_PLAYER_ID par l'id d'un user (joueur)
GET {{baseUrl}}/join-requests/my/?player_id=aaf3dcaa-39ce-40d0-9caf-11b6a10ce51f
Content-Type: application/json


### ================================
### 3) Voir les demandes reçues (organisateur)
### ================================
### Remplace ICI_ORGANIZER_ID par l'id d'un user organisateur
GET {{baseUrl}}/join-requests/received/?organizer_id=fb9ad348-d532-4849-90c3-a0135fb9ab5c
Content-Type: application/json


### ================================
### 4) Accepter une demande
### ================================
### Remplace ICI_JOINREQUEST_ID par l'id d'une join request
PATCH {{baseUrl}}/join-requests/daba24e2-e7da-4c21-9490-4f19a2381764/
Content-Type: application/json

{
  "status": "accepted"
}


### ================================
### 5) Refuser une demande
### ================================
PATCH {{baseUrl}}/join-requests/daba24e2-e7da-4c21-9490-4f19a2381764/
Content-Type: application/json

{
  "status": "rejected"
}
