# Generated by Django 5.0.1 on 2025-11-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('favorite_sport', models.CharField(max_length=50, verbose_name='Sport Favori')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to='users.user')),
            ],
            options={
                'verbose_name': 'Profil Joueur',
                'verbose_name_plural': 'Profils Joueurs',
                'db_table': 'player_profiles',
            },
        ),
    ]
