<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-23 17:25
=======
# Generated by Django 5.0.1 on 2025-11-23 19:39
>>>>>>> 122f80790f436918182e0f6bd8957115d31c88f0

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='users.user')),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
    ]
