# Generated by Django 5.0 on 2025-11-21 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("sport", models.CharField(blank=True, max_length=50, null=True)),
                ("capacity", models.PositiveIntegerField(default=11)),
                (
                    "tournament_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="teams", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
