# Generated by Django 5.2.8 on 2025-11-23 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'équipe")),
                ('max_capacity', models.IntegerField(default=15, verbose_name='Capacité maximale')),
                ('current_capacity', models.IntegerField(default=0, verbose_name='Capacité actuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='users.user', verbose_name="Membres de l'équipe")),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament', verbose_name='Tournoi associé')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'db_table': 'teams',
                'ordering': ['name', 'tournament'],
            },
        ),
    ]
