# Generated by Django 5.0.1 on 2025-11-23 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_id', models.CharField(max_length=255, unique=True, verbose_name='Clerk ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('player', 'Joueur'), ('organizer', 'Organisateur')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utilisateur Clerk',
                'verbose_name_plural': 'Utilisateurs Clerk',
                'db_table': 'users',
                'ordering': ['created_at'],
            },
        ),
    ]
