# Generated by Django 5.2.8 on 2025-11-23 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date et heure du match')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('score_a', models.IntegerField(blank=True, null=True, verbose_name='Score Équipe A')),
                ('score_b', models.IntegerField(blank=True, null=True, verbose_name='Score Équipe B')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'db_table': 'matches',
                'ordering': ['date'],
            },
        ),
    ]
