# Generated by Django 5.0.1 on 2025-11-23 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date et heure du match')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('score_a', models.IntegerField(blank=True, null=True, verbose_name='Score Équipe A')),
                ('score_b', models.IntegerField(blank=True, null=True, verbose_name='Score Équipe B')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='teams.team', verbose_name='Équipe A')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='teams.team', verbose_name='Équipe B')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'db_table': 'matches',
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('team_a', models.F('team_b')), _negated=True), name='teams_must_be_different'),
        ),
    ]
